#!/bin/sh -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SOURCE_PATH="${DIR}/.."
DEST_PATH="${DIR}/../builds"

if [ ! -d "${DEST_PATH}" ]; then
  mkdir "${DEST_PATH}"
fi

cd "${SOURCE_PATH}"

now=$(date +"%d_%m_%Y_%H_%M_%S")
DEST_FULL_PATH="${DEST_PATH}/hologram_server_${now}.tgz"
tar czvfh "${DEST_FULL_PATH}" PythonServer bin apps security/generate.sh
echo "Resulting package written to: ${DEST_FULL_PATH}"

exit 0
